=== Getting some information about unknown project
by Tomas Svarovsky

==== Problem
You just got invited to this project and just can't reach the project's author. Can't find any project's documentation. The following code snippet may be helpful in such situation

==== Solution
You want to start with a quick introspection. How many datasets, how much data is there how many processes etc. Doing this manually is fairly time consuming. You have to find the primary attributes of each dataset create a count metric and a lot of other stuff. This can be automated and it is so useful we actually created a command that does just this.

[source,ruby]
----
# encoding: utf-8

require 'gooddata'

GoodData.with_connection do |c|
  GoodData.with_project('project_pid') do |project|
    project.info
  end
end
----

This might be the hypothetical output. For each dataset you have there the size. Below is a breakdown of how many different types of objects there are inside the dataset.

[source,text]
----
GOODSALES
===============

Datasets - 28

stage_history
=============
Size - 29103.0 rows
1 attributes, 4 facts, 8 references

opp_snapshot
============
Size - 2130074.0 rows
1 attributes, 9 facts, 21 references

.
.
.
.

Opp_changes
===========
Size - 472.0 rows
2 attributes, 6 facts, 10 references

Opportunity Benchmark
=====================
Size - 487117.0 rows
3 attributes, 2 facts, 2 references
----
