=== Removing date facts
by Tomas Svarovsky

==== Problem
Not too recently Date fact was the only way how to compute with dates and get answers like "Give me number of days an order was opened". For some time now you can do the same computations with attributes. This can simplify your ETL and model a bit so why not to give it a try. Unfortunately people are often scared of how much work that might be.

==== Solution
Before we start tackling that let's first try to look around and see how much work is ahead of us. Removing Date facts can be only partially automated so it is good to have an idea if you can do this in a day or hire an army of interns for 2 weeks.

[source,ruby]
----
# encoding: utf-8

require 'gooddata'

GoodData.with_connection('user', 'password') do |client|
  project = GoodData.use('project_id')

  project = GoodData.use('project_id')
  blueprint = project.blueprint

  # NEED TO BE CHECKED PROBABLY DOES NOT WORK OUT OF THE BOX
  blueprint.date_facts.count
  blueprint.date_facts.each { |df| puts df[:name] }
end
----

Here you see how many date facts you have. This is the easy part. You can easily just delete them automatically. But we also need to have in how many metrics the date facts are used directly.

[source,ruby]
----
# encoding: utf-8

require 'gooddata'

GoodData.with_connection('user', 'password') do |client|
  project = GoodData.use('project_id')

  # Used BY.

end
----

==== Discussion