=== Specifying data type in the blueprint
by Tomas Svarovsky

==== Problem
You would like to specify a different data type in a blueprint

==== Solution

Each column in blueprint is eventually translated into a physical column in a database. While the defaults are typically what you want sometimes it might be useful to override them. You can specify the data type with gd_data_type clause.

[source,ruby]
----
# encoding: utf-8

require 'gooddata'

client = GoodData.connect

logger = Logger.new(STDOUT)
logger.level = Logger::DEBUG
GoodData.logger = logger

blueprint = GoodData::Model::ProjectBlueprint.build('Acme project') do |p|
  p.add_date_dimension('committed_on')

  p.add_dataset('commits') do |d|
    d.add_fact('lines_changed')
	  d.add_attribute('name', gd_data_type: 'INT')
    d.add_date('committed_on', :dataset => 'committed_on')
  end
end

# This is going to fail since we are trying to upload 1.2 into INT numeric type
data = [['lines_changed', 'name', 'committed_on'],
        [1.2, 'tomas', '01/01/2001']]
project.upload(data, blueprint, 'commits')

# This is going to pass since we are trying to upload 1 into INT numeric type
data = [['lines_changed', 'name', 'committed_on'],
        [1, 'tomas', '01/01/2001']]
project.upload(data, blueprint, 'commits')

----

==== Discussion

These data types that are supported on the platform

DECIMAL(m, d)
INTEGER
LONG
VARCHAR(n)

The case where this is very useful are

- if you use values from smaller domain (for example integers) you can leverage appropriate data type to save space and speed things up
- if you are using facts with atypical precision (the default is DECIMAL(12,2)) you can leverage decimal type with larger precision